# Generated by Django 5.0.6 on 2025-08-22 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snapshot',
            name='cores',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='snapshot',
            name='os',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='snapshot',
            name='processor',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='snapshot',
            name='ram_available',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='snapshot',
            name='ram_total',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='snapshot',
            name='ram_used',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='snapshot',
            name='threads',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
