# Generated by Django 5.0.6 on 2025-08-22 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_snapshot_cores_snapshot_os_snapshot_processor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snapshot',
            name='os',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='snapshot',
            name='processor',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
