# Generated by Django 5.0.6 on 2025-08-22 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_alter_snapshot_os_alter_snapshot_processor'),
    ]

    operations = [
        migrations.AddField(
            model_name='snapshot',
            name='storage_free',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='snapshot',
            name='storage_total',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='snapshot',
            name='storage_used',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
