# Generated by Django 5.0.6 on 2025-08-22 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0004_snapshot_storage_free_snapshot_storage_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='snapshot',
            name='system_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
